'use strict';

/**
 * modules/githubWriter.ts — GitHub Branch, Commit & Draft PR Creator
 */

import { Octokit } from '@octokit/rest';

export interface PRCreateOptions {
  productRepo: string;
  productOwner?: string;
  description: string;
  filePath: string;
  fileContent: string;
  taskBrief: Record<string, string>;
}

export interface PullRequestSummary {
  id: number | string;
  type: string;
  product: string;
  summary: string;
  actor: string;
  branch: string;
  status: string;
  date: string;
  url: string;
}

/**
 * createDraftPR(options)
 */
export async function createDraftPR(options: PRCreateOptions): Promise<string> {
  const { productRepo, productOwner, description, filePath, fileContent, taskBrief } = options;

  const githubToken = process.env.GITHUB_TOKEN;
  const githubOrg   = productOwner || process.env.GITHUB_ORG;

  if (!githubToken || !githubOrg) {
    throw new Error('GITHUB_TOKEN or GITHUB_ORG not set in .env');
  }

  const octokit = new Octokit({ auth: githubToken });

  console.log(`\n[GitHub Writer] Preparing Draft PR for ${productRepo}...`);

  // 1. Get the SHA of the latest commit on 'main'
  const mainRef = await octokit.rest.git.getRef({
    owner: githubOrg,
    repo: productRepo,
    ref: 'heads/main'
  });
  const latestSha = mainRef.data.object.sha;

  // 2. Create the feature branch
  const dateStr = new Date().toISOString().split('T')[0].replace(/-/g, '');
  const slug = description.toLowerCase().replace(/[^a-z0-9]/g, '-').substring(0, 30);
  const branchName = `agent/${slug}-${dateStr}`;

  console.log(`  [Writer] Creating branch: ${branchName}`);
  await octokit.rest.git.createRef({
    owner: githubOrg,
    repo: productRepo,
    ref: `refs/heads/${branchName}`,
    sha: latestSha
  });

  // 3. Commit the file
  console.log(`  [Writer] Committing code to: ${filePath}`);
  
  let currentFileSha: string | undefined;
  try {
    const fileData = await octokit.rest.repos.getContent({
      owner: githubOrg,
      repo: productRepo,
      path: filePath,
      ref: branchName
    });
    // @ts-ignore
    currentFileSha = fileData.data.sha;
  } catch (e) {
    // 404 is fine
  }

  await octokit.rest.repos.createOrUpdateFileContents({
    owner: githubOrg,
    repo: productRepo,
    path: filePath,
    message: `Agent task: ${description}`,
    content: Buffer.from(fileContent).toString('base64'),
    branch: branchName,
    sha: currentFileSha
  });

  // 4. Create Draft Pull Request
  console.log(`  [Writer] Opening Draft PR...`);

  const prBody = `
## Task Summary
${taskBrief['Description'] || 'No description provided.'}

## Changes Made
- Auto-generated code for ${filePath} based on provided brief.

## Testing Performed
- [Agent] Syntax validation only. Human review mandatory.

## Acceptance Criteria Check
${taskBrief['Acceptance Criteria'] || 'Review against criteria.'}

## Security & Privacy Flags
- **Priority:** ${taskBrief['Priority'] || 'Standard'}
- **Do Not Touch Violations:** None detected by agent.

---
*Generated by ASC Agent Service*
`.trim();

  const pr = await octokit.rest.pulls.create({
    owner: githubOrg,
    repo: productRepo,
    title: `[Agent] ${description}`,
    head: branchName,
    base: 'main',
    body: prBody,
    draft: true
  });

  console.log(`  [Writer] ✅ Draft PR opened: ${pr.data.html_url}\n`);

  return pr.data.html_url;
}

/**
 * getPullRequests(productRepo, productOwner)
 * Fetches both commits (representing Pushes) and Pull Requests to audit who is pushing/pulling.
 */
export async function getPullRequests(productRepo: string, productOwner?: string): Promise<PullRequestSummary[]> {
  const githubToken = process.env.GITHUB_TOKEN;
  const githubOrg   = productOwner || process.env.GITHUB_ORG;

  if (!githubToken || !githubOrg) return [];

  const octokit = new Octokit({ auth: githubToken });
  const activityList: PullRequestSummary[] = [];

  // 1. Fetch Pull Requests
  try {
    const { data: pullRequests } = await octokit.rest.pulls.list({
      owner: githubOrg,
      repo: productRepo,
      state: 'all',
      sort: 'updated',
      direction: 'desc',
      per_page: 20
    });

    pullRequests.forEach(pr => {
      activityList.push({
        id: `PR #${pr.number}`,
        type: 'Pull Request',
        product: productRepo,
        summary: pr.title,
        actor: pr.user?.login || 'unknown',
        branch: pr.head.ref,
        status: pr.merged_at ? 'Merged' : pr.state.charAt(0).toUpperCase() + pr.state.slice(1),
        date: pr.created_at ? pr.created_at.split('T')[0] : 'N/A',
        url: pr.html_url
      });
    });
  } catch (e: any) {
    console.warn(`[GitHub Writer] Failed to fetch PRs for ${productRepo}: ${e.message}`);
  }

  // 2. Fetch Commits (Pushes) on main
  try {
    const { data: commits } = await octokit.rest.repos.listCommits({
      owner: githubOrg,
      repo: productRepo,
      sha: 'main',
      per_page: 20
    });

    commits.forEach(c => {
      activityList.push({
        id: c.sha.substring(0, 7),
        type: 'Push',
        product: productRepo,
        summary: c.commit.message.split('\n')[0],
        actor: c.author?.login || c.commit.author?.name || 'unknown',
        branch: 'main',
        status: 'Pushed',
        date: c.commit.author?.date ? c.commit.author.date.split('T')[0] : 'N/A',
        url: c.html_url
      });
    });
  } catch (e: any) {
    console.warn(`[GitHub Writer] Failed to fetch commits for ${productRepo}: ${e.message}`);
  }

  return activityList;
}

